.include {setup.qmd}

.include {header.qmd}

.tableofcontents

# Analisi dei requisiti

[Inserire qui la descrizione del progetto.]

## Intervista

[Inserire qui il testo dell'intervista con il cliente.]


## Rilevamento delle ambiguità e correzioni proposte

[Inserire qui le ambiguità rilevate nel testo dell'intervista e le correzioni proposte.]

.tablesort {1}
    .csv {tables/concepts.csv} caption:{concetti.}


## Definizione delle specifiche in linguaggio naturale ed estrazione dei concetti principali

[Inserire qui il riassunto dell'intervista con le correzioni]

[Elenco con le operazioni definite]
- op1
- op2


# Progettazione Concettuale

## Schema scheletro

[Inserire qui lo schema scheletro del database.]

## Raffinamenti proposti

[Inserire qui i raffinamenti proposti allo schema scheletro.]

## Schema concettuale finale

[Inserire qui lo schema concettuale finale del database.]



# Progettazione logica

## Stima del volume dei dati

[Inserire qui la stima del volume dei dati.]

## Descrizione delle operazioni principali e stima della loro frequenza

[Inserire qui la descrizione delle operazioni principali e la stima della loro frequenza.]

## Schemi di navigazione e tabelle degli accessi

[Inserire qui gli schemi di navigazione e le tabelle degli accessi.]

## Raffinamento dello schema

### Eliminazione di identificatori esterni, attributi composti e gerarchie, scelta delle chiavi

[Inserire qui il testo relativo al raffinamento dello schema.]

## Analisi delle ridondanze

[Inserire qui l'analisi delle ridondanze.]

## Traduzione di entità e associazioni in relazioni

[Inserire qui la traduzione di entità e associazioni in relazioni.]

## Schema relazionale finale

[Inserire qui lo schema relazionale finale.]

## Traduzione delle operazioni in query SQL

[Inserire qui la traduzione delle operazioni in query SQL.]



# Progettazione dell'applicazione

## Descrizione dell'architettura dell'applicazione realizzata

[Inserire qui la descrizione dell'architettura dell'applicazione realizzata, con screenshot dell'interfaccia utente.]
